webtalk_init -webtalk_dir C:/Users/hyeon/project_19-2/19_2_soc_design/work/FFFFFT/FFFFFT.sim/sim_1/behav/xsim/xsim.dir/tb_Top_FFT_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 20 02:58:18 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2117270" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210862093_1777503669_210691714_648" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ff467257-f647-4436-a7d4-879934f1f65a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "efa859acfc16402a843d7ca389271ae7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 1600 Six-Core Processor            " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6904_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1569124297 -regid "210862093_1777503669_210691714_648" -xml C:/Users/hyeon/project_19-2/19_2_soc_design/work/FFFFFT/FFFFFT.sim/sim_1/behav/xsim/xsim.dir/tb_Top_FFT_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/hyeon/project_19-2/19_2_soc_design/work/FFFFFT/FFFFFT.sim/sim_1/behav/xsim/xsim.dir/tb_Top_FFT_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/hyeon/project_19-2/19_2_soc_design/work/FFFFFT/FFFFFT.sim/sim_1/behav/xsim/xsim.dir/tb_Top_FFT_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
